import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "../context/ThemeContext"

import { ReactNode } from "react";
// builded after dashboard
import { Inter } from "next/font/google"
const inter = Inter({ subsets: ["latin"] })

import { Toaster } from 'react-hot-toast';


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white dark:bg-zinc-900 text-zinc-900 dark:text-white transition-colors duration-300`}>
        
      <Toaster position="top-center" />

        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
