"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "../context/ThemeContext"

import { Provider } from 'react-redux';

import { ReactNode } from "react";
// builded after dashboard
import { Inter } from "next/font/google"
const inter = Inter({ subsets: ["latin"] })

import { Toaster } from 'react-hot-toast';
import store from "@/store/patient/authStore";


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Provider>
  );
}
